### ISSUE TITLE
lateinit property smsChannel has not been initialized

### ISSUE THREAD

**Issue by zmmmken** [shounakmulay/Telephony#37] opened 2020-11-15 17:38 UTC
when uninstall app and reinstall it i have this issue :

E/AndroidRuntime(13514): kotlin.UninitializedPropertyAccessException: lateinit property smsChannel has not been initialized
E/AndroidRuntime(13514): 	at com.shounakmulay.telephony.TelephonyPlugin.tearDownPlugin(TelephonyPlugin.kt:68)
E/AndroidRuntime(13514): 	at com.shounakmulay.telephony.TelephonyPlugin.onDetachedFromEngine(TelephonyPlugin.kt:34)
E/AndroidRuntime(13514): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime(13514): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime(13514): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime(13514): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime(13514): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime(13514): 	at be.tramckrijte.workmanager.BackgroundWorker$stopEngine$1.run(BackgroundWorker.kt:117)
E/AndroidRuntime(13514): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(13514): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13514): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(13514): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime(13514): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13514): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(13514): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by shounakmulay** [comment] 2020-11-15 17:49
Hey @zmmmken ,

Will look into it.

It will really help me if you could provide some more details like
- steps to reproduce
- flutter doctor output
- Version of plugin and if possible details about if this issue only happen with the latest plugin version or on earlier versions as well.

Thanks.

**Comment by zmmmken** [comment] 2020-11-15 18:54
above issue is happen in version 0.0.5, in other versions this problem is exist

flutter Doctor:
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.49.2)
[√] Connected device (1 available)

**Comment by shounakmulay** [comment] 2020-11-17 03:19
Thanks for the details @zmmmken 

I tried uninstalling and reinstalling but unfortunately I was not able to reproduce this issue.
It would be really helpful if you could provide me with instructions on how to reproduce this or if possible provide a recording or gif of how to reproduce the issue.

**Comment by shounakmulay** [comment] 2020-11-24 13:33
Closing this for now.

**Closed as completed by shounakmulay** 2020-11-24 13:33 UTC
Labels: bug, could not reproduce
