### ISSUE TITLE
Error with Flutter 2.2.0

### ISSUE THREAD

**Issue by mustafa-fahimi** [shounakmulay/Telephony#85] opened 2021-05-20 17:12 UTC
Hi. Since I updated Flutter to 2.2.0 I get this error and can't use this package.
Error: telephony-0.1.3\android\src\main\kotlin\com\shounakmulay\telephony\sms\SmsMethodCallHandler.kt: (52, 62): Expecting a parameter declaration

**Comment by shounakmulay** [comment] 2021-05-21 02:36
Duplicate of #84

I will remove the trailing commas in next release.

**Comment by Tokenizer94** [comment] 2021-05-21 21:33
@shounak-mulay Thanks, man. But when will be the next release? I want to use your package but I can't right now.

**Comment by shounakmulay** [comment] 2021-05-23 03:58
Fixed in [v0.1.4](https://pub.dev/packages/telephony/versions/0.1.4)

**Closed as completed by shounakmulay** 2021-05-23 03:58 UTC
Labels: duplicate
