### ISSUE TITLE
An error occurs when send SMS in background

### ISSUE THREAD

**Issue by cuongdl** [shounakmulay/Telephony#51] opened 2021-01-30 16:22 UTC
Hi Team,

When receive SMS in Background, I send another SMS but I got this error:
 _[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method sendSms on channel plugins.shounakmulay.com/foreground_sms_channel)
E/flutter (24790): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (24790): <asynchronous suspension>
E/flutter (24790): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (24790): #2      Telephony.sendSms (package:telephony/telephony.dart:315:30)
E/flutter (24790): #3      forwardMessages (package:FwSms/main.dart:59:19)
E/flutter (24790): <asynchronous suspension>
E/flutter (24790): #4      onBackgroundMessage (package:FwSms/main.dart:76:3)
E/flutter (24790): #5      _flutterSmsSetupBackgroundChannel.<anonymous closure> (package:telephony/telephony.dart:27:30)
E/flutter (24790): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (24790): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (24790): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (24790): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (24790): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24790): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24790): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24790): #13     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (24790): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)_

If I open the app, it works fine.

Thank you very much.

Best,
Cuong

**Comment by dinahapuque** [comment] 2021-03-05 18:45
I'm also getting this exception when using this package with WorkManager and AndroidAlarmManager ):

**Comment by shounakmulay** [comment] 2021-03-06 04:25
Hey @cuongdl @dinahapuque 

I was not able to reproduce this issue.
I could correctly receive SMS in background on an emulator as well as on a physical device.
Could you please provide a reproducible example that I can look into?

**Comment by kakajansh** [comment] 2021-03-07 09:00
@shounakmulay they are about **sending** SMS in background. We also encounter this problem. We have firebase configured, and when receive background notification we want to send SMS.

```dart
final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
final Telephony telephony = Telephony.instance;

@override
void initState() {
  initFirebase();
  super.initState();
}

initFirebase() async {
  await telephony.requestPhoneAndSmsPermissions;
  _firebaseMessaging.requestNotificationPermissions();
  _firebaseMessaging.subscribeToTopic('verify');
  _firebaseMessaging.configure(
    onBackgroundMessage: _onBackgroundMessage,
    onMessage: (Map<String, dynamic> notification) async {
      String phone = notification['data']['phone'];
      String message = notification['data']['body'];

      telephony.sendSms(to: phone, message: message);
    },
  );
}
```
`onMessage` fires only when app is open, and it works. But on `onBackgroundMessage` it throws above `MissingPluginException` error.

```dart
Future<dynamic> _onBackgroundMessage(
  Map<String, dynamic> notification,
) async {
  final String phone = notification['data']['phone'];
  final String message = notification['data']['body'];

  Telephony.instance.sendSms(to: phone, message: message);

  return Future<void>.value();
}
```

**Comment by shounakmulay** [comment] 2021-03-07 09:06
@kakajansh Thanks for the explanation.
I guess I had an incorrect understand of the problem. 
Will take a look and update here.

**Comment by dinahapuque** [comment] 2021-03-10 18:52
Using AndroidAlertManager causes the same error:

```(MissingPluginException(No implementation found for method sendSms on channel plugins.shounakmulay.com/foreground_sms_channel))```

E.g:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final int helloAlarmID = 0;
  await AndroidAlarmManager.initialize();

  runApp(App());

  await AndroidAlarmManager.periodic(
    const Duration(minutes: 1),
    helloAlarmID,
    sendSms,
    wakeup: true,
  );
}

Future<void> sendSms() async {
  try {
    Telephony.instance.sendSms(
        to: myPhone,
        message: myMessage;
  } catch (e) {
    print(e);
  }
}
```

**Comment by shivanshPurple** [comment] 2021-03-19 07:21
Any updates!? I am also having the same problem when I try to send a SMS in the background by an android service

**Comment by tareqfaris** [comment] 2021-03-25 01:23
I also have the same problem, is there a solution?

**Comment by shounakmulay** [comment] 2021-03-26 07:45
I think the problem is that when the app is in background, the plugin initialization does not happen correctly on the android side.
Also if you app is still active in background, call the plugin from the background makes it loose the reference to the original method channel that is used as a communication bridge.

Maybe adding a `backgroundInstance` to call telephony methods from the background could be the solution. This way we don't make the original instance inactive and you can still continue using it once the app comes back to the foreground.

**Comment by shounakmulay** [comment] 2021-03-28 13:43
This is fixed in [v0.1.1](https://pub.dev/packages/telephony/versions/0.1.1).

Checkout https://github.com/shounakmulay/Telephony/tree/v0.1.1#executing-in-background

**Comment by kakajansh** [comment] 2021-03-29 16:44
@shounakmulay For me it doesn't work with firebase background handler. But works when receiving sms in background. 

__This one works__
```dart
telephony.listenIncomingSms(
  onNewMessage: (SmsMessage message) { ... },
  onBackgroundMessage: backgroundMessageHandler,
);

backgroundMessageHandler(SmsMessage message) async {
  Telephony.backgroundInstance.sendSms(to: "123456789", message: "Message from background");
}
```

__This one throws__ `Unhandled Exception: MissingPluginException(No implementation found for method sendSms on channel plugins.shounakmulay.com/foreground_sms_channel)`
```dart
// foreground
FirebaseMessaging.onMessage.listen((RemoteMessage notification) async {
      ...
      Telephony.instance.sendSms(to: phone, message: msg);
});

// background
FirebaseMessaging.onBackgroundMessage(onBackgroundMessage);

Future<void> _onBackgroundMessage(RemoteMessage message) async {
  final String phone = message.data['phone'];
  final String body = message.data['body'];

  Telephony.backgroundInstance.sendSms(to: phone, message: body);
}
```

Could you please direct what is missing here. There are some other issues maybe related to this about mixing plugins.
[How to make Flutter Workmanager plugin and Location plugin work together](https://stackoverflow.com/questions/60262425/how-to-make-flutter-workmanager-plugin-and-location-plugin-work-together)

**Comment by shounakmulay** [comment] 2021-03-29 16:55
@kakajansh will take a look.
Would be great if you could give me some more info like does this happen only with the firebase messaging plugin or does it happen with other plugins as well?
Thanks.

**Comment by shounakmulay** [comment] 2021-04-23 14:42
Closing this for now. Feel free to reopen with any updates.

**Closed as completed by shounakmulay** 2021-04-23 14:42 UTC
Labels: bug

**Comment by sharifka** [comment] 2022-05-22 08:10
i have an error about using backgroundMessageHandler
Telephony.backgroundInstance.dialPhoneNumber('12345');
Telephony.instance.dialPhoneNumber('1234');
not works,but when used foreground is working fine.
what is the error,please any can helpe to fix this error.
