### ISSUE TITLE
An error occurs when reciving SMS in background or in foreground causes the app to crash

### ISSUE THREAD

**Issue by mohanedy** [shounakmulay/Telephony#63] opened 2021-03-16 21:03 UTC
**every time I receive SMS while the app in foreground or background the app crash throwing this exception:**
```
 Process: com.iraq.caller.iraq_caller, PID: 13768
E/AndroidRuntime(13768): java.lang.RuntimeException: Unable to start receiver com.shounakmulay.telephony.sms.IncomingSmsReceiver: java.lang.NullPointerException: FlutterCallbackInformati…formation(callbackHandle) must not be null
E/AndroidRuntime(13768): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4092)
E/AndroidRuntime(13768): 	at android.app.ActivityThread.access$1500(ActivityThread.java:246)
E/AndroidRuntime(13768): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1985)
E/AndroidRuntime(13768): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13768): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13768): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13768): 	at android.app.ActivityThread.main(ActivityThread.java:7729)
E/AndroidRuntime(13768): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13768): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13768): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
E/AndroidRuntime(13768): Caused by: java.lang.NullPointerException: FlutterCallbackInformati…formation(callbackHandle) must not be null
E/AndroidRuntime(13768): 	at com.shounakmulay.telephony.sms.IncomingSmsHandler.startBackgroundIsolate(IncomingSmsHandler.kt:141)
E/AndroidRuntime(13768): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processInBackground(IncomingSmsHandler.kt:89)
E/AndroidRuntime(13768): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processIncomingSms(IncomingSmsHandler.kt:78)
E/AndroidRuntime(13768): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.onReceive(IncomingSmsHandler.kt:48)
E/AndroidRuntime(13768): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4083)
E/AndroidRuntime(13768): 	... 9 more
```
**and here's my flutter doctor -v:** 

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale en-EG)
    • Flutter version 2.0.1 at /Users/mohanedy/Dev/flutter
    • Framework revision c5a4b4029c (12 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mohanedy/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mohanedy/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

Thanks in advance

**Comment by shounakmulay** [comment] 2021-03-29 02:59
Hey @Mohanedy98 

Would be great if you could provide me with a reproducible example that I can run on my end and investigate the error.

**Comment by shounakmulay** [comment] 2021-04-23 14:40
Closing this for now. Feel free to reopen.

**Closed as completed by shounakmulay** 2021-04-23 14:40 UTC
Labels: could not reproduce

**Comment by yolowex** [comment] 2024-01-07 20:11
I have the same problem.
It happened without any particular reason.
all my previous commits too. 
I don't know why
here is full details on my problem
my flutter doctor is ok too

```dart
D/AndroidRuntime(19650): Shutting down VM
E/AndroidRuntime(19650): FATAL EXCEPTION: main
E/AndroidRuntime(19650): Process: com.irstake.webviewApp, PID: 19650
E/AndroidRuntime(19650): java.lang.RuntimeException: Unable to start receiver com.shounakmulay.telephony.sms.IncomingSmsReceiver: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
E/AndroidRuntime(19650): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4770)
E/AndroidRuntime(19650): 	at android.app.ActivityThread.access$1700(ActivityThread.java:310)
E/AndroidRuntime(19650): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
E/AndroidRuntime(19650): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19650): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(19650): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(19650): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(19650): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19650): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(19650): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(19650): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
E/AndroidRuntime(19650): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:421)
E/AndroidRuntime(19650): 	at java.lang.String.valueOf(String.java:3657)
E/AndroidRuntime(19650): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(19650): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
E/AndroidRuntime(19650): 	at com.shounakmulay.telephony.sms.IncomingSmsHandler.startBackgroundIsolate(IncomingSmsHandler.kt:154)
E/AndroidRuntime(19650): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processInBackground(IncomingSmsHandler.kt:95)
E/AndroidRuntime(19650): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processIncomingSms(IncomingSmsHandler.kt:82)
E/AndroidRuntime(19650): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.onReceive(IncomingSmsHandler.kt:50)
E/AndroidRuntime(19650): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4761)
E/AndroidRuntime(19650): 	... 9 more
```

I get this error whenever an sms message is recieved.
it happens in this function, the stack trace does not point to anything in the function, even if the function is empty, I still get this error.

```java
public class SmsListenerService extends Service {
  // this is a java android service that I'm running, it is a foreground service.
  ...
private void handleSmsReceived(Intent intent) {
        // problem happens here
        // whenever an sms message is received this method is called
        // the stack trace doesn't point to this nor anything in my code
    }
  ...
}
```

# **Important note**

please note that I didn't encounter this error yesterday at all! 
I tried falling back to previous commits and check if the error is still there, and the error is everywhere!
even on the commits that I know are stable and *worked*.

so in short, something weird happened. I didn't touch my project since yesterday and it is ruined, and I don't know why, and all of the commits are ruined too. 

What the hell is going on?

Edit:
I tried upgrading flutter but no help, I tried flutter clean but nothing changed, this happend suddenly, my code worked, 
i didn't change anything, it showed up with no reason



flutter doctor just in case:

```terminal
[✓] Flutter (Channel stable, 3.16.5, on Kali GNU/Linux Rolling 6.4.0-kali3-amd64, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/yolo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/yolo/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /home/yolo/android-studio-chipmunk/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.0)
    • Android Studio at /home/yolo/android-studio-old
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "1.8.0_152-release"

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/yolo/android-studio-chipmunk
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.12" 2021-07-20

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/yolo/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.6008.13
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /home/yolo/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9011.34
    • Flutter plugin version 74.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM A225F (mobile) • R58R918KD3B • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Kali GNU/Linux Rolling 6.4.0-kali3-amd64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.


```

**Comment by yolowex** [comment] 2024-01-07 20:18
> Hey @Mohanedy98
> 
> Would be great if you could provide me with a reproducible example that I can run on my end and investigate the error.

if you want I can send you a copy of my app, so you can investigate

```java
package com.irstake.webviewApp;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Build;
import android.os.Bundle;
import android.os.IBinder;
import android.util.Log;

import androidx.core.app.NotificationCompat;

public class SmsListenerService extends Service {

    private static final String TAG = "SmsService";
    private SmsReceiver smsReceiver;
    private static final int NOTIFICATION_ID = 123;

    @Override
    public void onCreate() {
        super.onCreate();

        smsReceiver = new SmsReceiver();
        IntentFilter filter = new IntentFilter("android.provider.Telephony.SMS_RECEIVED");
        registerReceiver(smsReceiver, filter);

        startForeground(NOTIFICATION_ID, createNotification());
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        // Service logic goes here
        return START_STICKY;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        unregisterReceiver(smsReceiver);
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    private Notification createNotification() {
        // Create a notification for the foreground service
        // Customize this method to create a notification that suits your app
        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, "channel")
                .setContentTitle("text")
                .setSmallIcon(android.R.drawable.ic_dialog_info)
                .setContentText("text")
                .setPriority(NotificationCompat.PRIORITY_HIGH)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC);

        Notification notification =  builder.build();
        Log.i(TAG,"notification " + notification);
        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.notify(NOTIFICATION_ID, notification);
        return notification;
    }

    public class SmsReceiver extends BroadcastReceiver {

        @Override
        public void onReceive(Context context, Intent intent) {
            Bundle bundle = intent.getExtras();

            if (bundle != null) {
                Object[] pdus = (Object[]) bundle.get("pdus");

                if (pdus != null) {
                    for (Object pdu : pdus) {
                    }
                }
            }
        }
    }
}
```

I tried using something other than telephony.
but I still get the telephony error :/
the same thing.
but pay attention to my important note up there, I think the problem is something external.
because I am **Sure** that my project ran smoothly yesterday. (I changed nothing)

**Comment by yolowex** [comment] 2024-01-07 20:54
> Hey @Mohanedy98
> 
> Would be great if you could provide me with a reproducible example that I can run on my end and investigate the error.

if you want I can send you a copy of my app, so you can investigate

**Comment by ashwin-dailype** [comment] 2024-02-27 12:41
I'm facing the same crash. Linking some relevant data below


#### Stack trace
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.shounakmulay.telephony.sms.IncomingSmsReceiver: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4903)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8779)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

#### Relevant code snippet
```dart

@pragma('vm:entry-point')
backgroundMessageHandler(message) async {
  String? smsUrl;
  String? env = await PreferencesHelper.prefGetString(PreferencesHelper.env);
  try {
    smsUrl =
        (await PreferencesHelper.prefGetString(PreferencesHelper.ingestUrl)) +
            Endpoints.ingestSms;
  } catch (e, s) {
    debugPrint('Error in bg msg handler: $e');
    debugPrintStack(stackTrace: s);
  }
  syncSmsPeriodic(
      smsUrl, env);
}

@pragma('vm:entry-point')
registerBgSmsListener() async {
  await PreferencesHelper.prefSetString(PreferencesHelper.ingestUrl, ingestUrl);
  final Telephony telephony = Telephony.instance;
  telephony.listenIncomingSms(
      onNewMessage: (message) {
        backgroundMessageHandler(message);
      },
      onBackgroundMessage: backgroundMessageHandler);
}

```


#### Crashlytics stats of my app
<img width="1187" alt="image" src="https://github.com/shounakmulay/Telephony/assets/130335509/86c57503-fbb7-4cfd-931d-5a7fc28ddd7e">
